spring:
  application:
    name: rest-api-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/restapispring
    username: postgres
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
